const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],calls=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
 const state={ok:true,players:[{name:'A',status:'active'},{name:'B',status:'active'}],lineups:[],results:[],mvps:[],sanctions:[],deletedDates:[],playoffs:[],history:[],fund:{amount:0}},submissions=[];
 for(let number=1;number<=20;number++){state.lineups.push({matchNumber:number,date:'2026-10-10',white:['A'],black:['B']});if(number<20)state.results.push({matchNumber:number,whiteGoals:0,blackGoals:0,winner:'draw',played:true});if(number<19){state.mvps.push({matchNumber:number,player:'A'});for(let i=0;i<16;i++)submissions.push({id:`old-${number}-${i}`,matchNumber:number,player:i%2?'A':'B',goals:0,mvpVote:i%2?'B':'A',status:'approved',team:i%2?'white':'black'})}}
 for(let i=0;i<5;i++)submissions.push({id:`current-${i}`,matchNumber:19,player:i%2?'A':'B',goals:0,mvpVote:i%2?'B':'A',status:i<3?'approved':'pending',team:i%2?'white':'black'});
 const originalCount=submissions.length,fields={listWebPlayers:'players',listLineups:'lineups',listResults:'results',listMvp:'mvps',listSanctions:'sanctions',listDeletedDates:'deletedDates',listPlayoffs:'playoffs'};
 await page.route('https://fonts.googleapis.com/**',route=>route.fulfill({body:'',contentType:'text/css'}));
 await page.route('https://script.google.com/**',async route=>{const request=route.request();let response;if(request.method()==='GET'){calls.push('state');response=state}else{const body=JSON.parse(request.postData());calls.push(body.action);if(body.action==='list')response={ok:true,items:submissions};else if(fields[body.action])response={ok:true,items:state[fields[body.action]]};else if(body.action==='auth')response={ok:true,authenticated:true};else if(body.action==='confirmMvp'){const item={matchNumber:body.matchNumber,player:body.player};state.mvps.push(item);response={ok:true,item}}else throw new Error('Unexpected mock action '+body.action)}await route.fulfill({json:response,headers:{'access-control-allow-origin':'*'}})});
 await page.goto(process.env.CHIQUI_TEST_URL||'http://127.0.0.1:8000/');await page.waitForFunction(()=>document.querySelector('#syncStatus').textContent==='En vivo');await page.locator('#adminPin').fill('test-pin');await page.locator('#adminLoginForm button').click();await page.waitForFunction(()=>document.querySelector('#voteDateSummary').textContent.includes('Fecha 19'));
 assert.equal(await page.locator('#voteMatch').inputValue(),'19');assert.equal(await page.locator('#pendingGoals .pending-card').count(),2);assert.equal(await page.locator('#approvedGoals .pending-card').count(),3);assert.equal(await page.locator('#approvedDateCount').textContent(),'(3)');assert.equal(await page.locator('#approvedDeclarations').getAttribute('open'),null);assert((await page.locator('#voteDateSummary').textContent()).includes('3 votos MVP'));assert.equal(await page.locator('#mvpVoteResults .vote-row').count(),2);
 assert(await page.locator('#resultForm').isVisible());assert(!(await page.locator('#playoffForm').isVisible()));assert.equal(await page.locator('.admin-match-tools #playoffForm').count(),1);await page.locator('#playoffTools summary').click();assert(await page.locator('#playoffForm').isVisible());await page.locator('#playoffTools summary').click();assert(!(await page.locator('#sanctionForm').isVisible()));assert(!(await page.locator('#fundForm').isVisible()));await page.locator('#disciplineTools summary').click();assert(await page.locator('#sanctionForm').isVisible());await page.locator('#disciplineTools summary').click();await page.locator('#fundTools summary').click();assert(await page.locator('#fundForm').isVisible());await page.locator('#fundTools summary').click();
 assert.equal(await page.locator('.admin-match-tools #resultForm').count(),1);assert.equal(await page.locator('.admin-match-tools #sanctionForm').count(),1);assert.equal(await page.locator('.admin-match-tools #fundForm').count(),1);
 const beforeHistory=calls.length;await page.locator('#voteMatch').selectOption('1');await page.waitForFunction(()=>document.querySelector('#voteDateSummary').textContent.includes('Fecha 1 ·'));assert.equal(await page.locator('#pendingGoals .pending-card').count(),0);assert.equal(await page.locator('#approvedGoals .pending-card').count(),16);assert((await page.locator('#mvpVoteResults .official-mvp').textContent()).includes('A'));assert.equal(submissions.length,originalCount);assert.equal(calls.length,beforeHistory,'history reads reuse loaded submissions');await page.locator('#approvedDeclarations summary').click();assert(await page.locator('#approvedGoals').isVisible());
 await page.locator('#voteMatch').selectOption('20');await page.waitForFunction(()=>document.querySelector('#voteDateSummary').textContent.includes('Fecha 20'));assert.equal(await page.locator('#approvedGoals .pending-card').count(),0);assert.equal(await page.locator('#approvedDeclarations').getAttribute('open'),null);
 await page.locator('#voteMatch').selectOption('19');await page.waitForFunction(()=>document.querySelector('#voteDateSummary').textContent.includes('Fecha 19'));await page.locator('#mvpVoteResults .confirm-mvp').first().click();await page.waitForFunction(()=>document.querySelector('#mvpVoteResults .official-mvp'));assert.equal(state.mvps.at(-1).matchNumber,19);assert.equal(await page.locator('#voteMatch').inputValue(),'19');assert.equal(await page.locator('#approvedGoals .pending-card').count(),3);assert.equal(submissions.length,originalCount,'confirming MVP never removes historical declarations');
 await page.locator('#voteMatch').selectOption('1');await page.waitForFunction(()=>document.querySelector('#voteDateSummary').textContent.includes('Fecha 1 ·'));assert.equal(await page.locator('#approvedGoals .pending-card').count(),16);assert(await page.locator('.admin-match-tools').evaluate(element=>element.getBoundingClientRect().right<=innerWidth&&element.scrollWidth<=element.clientWidth));
 assert.deepEqual(errors,[]);console.log('PASS: 20 dates/293 declarations; default latest played voting date; only selected-date votes and declarations; old history preserved; approved lists collapse; history switches without extra API calls; MVP confirmation retains selected date; marker/discipline/fund grouped and fit mobile.');
 }finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
