const assert=require('node:assert/strict'),{chromium}=require('playwright'),{createBackend}=require('./apps-script-harness.cjs');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const b=createBackend({},'2026-10-04T15:00:00Z'),white=['LORIA','DIEGO','FRANCO','MATU','VALEN','MATI BILLO','DARIO','INVITADO'],black=['LUCAS','AUGUSTO','LIHUEL','PABLO','GONZA','AGUSREGGI','LAUTY','KEVIN'];
 for(const name of [...white,...black].filter(n=>n!=='INVITADO'))b.call('addPlayer',{pin:'test-pin',name});
 for(const [number,date] of [[2,'2026-10-03'],[3,'2026-10-10']])assert(b.call('saveLineup',{pin:'test-pin',item:{matchNumber:number,date,white,black}}).ok);
 const seed=b.call('saveResult',{pin:'test-pin',item:{matchNumber:2,whiteGoals:5,blackGoals:4,scorers:[{player:'LORIA',team:'white',goals:5},{player:'LUCAS',team:'black',goals:4}]}});assert(seed.ok);b.run('setupTournamentAutomation');
 // A legacy declaration of this same round must be replaced, not counted again.
 b.context.sheet_().appendRow(['legacy','2026-10-03',2,'2026-10-03','LORIA','white',8,'DIEGO','','approved','']);
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));let rejectVoteOnce=false;
 await context.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:'',contentType:'text/css'}));
 await context.route('https://script.google.com/**',r=>{let response;if(r.request().method()==='POST'){const body=JSON.parse(r.request().postData());calls.push(body);if(body.action==='voteMvp'&&rejectVoteOnce){rejectVoteOnce=false;response={ok:false,error:'Error simulado. Reintentá.'}}else response=b.call(body.action,body)}else response=b.state();return r.fulfill({json:response})});
 const ready=async()=>page.waitForFunction(()=>document.querySelector('#syncStatus').textContent==='En vivo');
 const points=name=>page.locator('#standingsBody tr').filter({has:page.locator('.player-cell>span:nth-child(2)',{hasText:new RegExp('^'+name+'$')})}).locator('td').nth(2).textContent();
 const open=async()=>{await page.locator('#mvpVotingPanel').scrollIntoViewIfNeeded()};
 const identify=async name=>{await page.locator('#mvpChooseVoter').click();await page.locator('#mvpVoterTeams .mvp-player').filter({hasText:new RegExp('^'+name+'Soy yo$')}).click()};
 const candidate=name=>page.locator('#mvpCandidateTeams .mvp-player').filter({has:page.locator('strong',{hasText:new RegExp('^'+name+'$')})});
 await page.goto(process.env.CHIQUI_TEST_URL||'http://127.0.0.1:8003/');await ready();await page.locator('#mvpVotingPanel').waitFor({state:'visible'});assert.equal(await page.locator('#legacyGoalSubmission').isVisible(),false);assert.equal(await page.locator('#votingTitle').textContent(),'Votación de MVP');assert.equal(await points('LORIA'),'3,5');assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).LORIA,5);
 assert(await page.locator('#mvpVotingPanel').evaluate(e=>e.getBoundingClientRect().height<=640));
 await open();assert.equal(await candidate('LORIA').locator('span').textContent(),'+');assert.equal(await page.locator('#mvpCandidateTeams .mvp-player').count(),16);
 await candidate('DIEGO').click();assert(await page.locator('#mvpConfirmVote').isDisabled());await identify('LORIA');assert(await candidate('LORIA').isDisabled());assert.equal(calls.filter(x=>x.action==='voteMvp').length,0,'selection alone never sends a vote');
 rejectVoteOnce=true;await page.locator('#mvpConfirmVote').click();await page.waitForFunction(()=>document.querySelector('#mvpVoteMessage').textContent.includes('Error simulado'));assert.equal(b.call('listMvpVotes',{pin:'test-pin'}).items.length,0);await page.locator('#mvpConfirmVote').click();await page.waitForFunction(()=>document.querySelector('#mvpVoteMessage').textContent.includes('ya está registrado'));assert.equal(b.call('listMvpVotes',{pin:'test-pin'}).items.length,1);assert(await candidate('LUCAS').isDisabled());assert(!await page.locator('#mvpConfirmation').isVisible());
 await page.reload();await ready();await open();assert((await page.locator('#mvpVoteMessage').textContent()).includes('ya está registrado'));
 // Switching identity cannot bypass the server's one-vote-per-participant rule.
 await identify('LORIA');await candidate('PABLO').click();await page.locator('#mvpConfirmVote').click();await page.waitForFunction(()=>document.querySelector('#mvpVoteMessage').textContent.includes('Ya votaste'));assert.equal(b.call('listMvpVotes',{pin:'test-pin'}).items.length,1);
 await identify('LUCAS');await candidate('PABLO').click();await page.locator('#mvpConfirmVote').click();await page.waitForFunction(()=>document.querySelector('#mvpVoteMessage').textContent.includes('ya está registrado'));assert.equal(b.call('listMvpVotes',{pin:'test-pin'}).items.length,2);
 assert.equal(await page.locator('#mvpClosedResult').isVisible(),false);assert(!JSON.stringify(b.state()).includes('candidate'),'new vote details are not public');
 for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:800});assert(await page.locator('#mvpVotingDialog').evaluate(e=>e.scrollWidth<=e.clientWidth&&e.getBoundingClientRect().right<=innerWidth));assert(await page.locator('.mvp-dialog-footer').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('#mvpVotingDialog').getBoundingClientRect().bottom));}
 await page.locator('#adminPin').fill('test-pin');await page.locator('#adminLoginForm button').click();await page.waitForFunction(()=>document.querySelector('#adminPanel').hidden===false);await page.locator('#voteMatch').selectOption('2');await page.waitForFunction(()=>document.querySelector('.mvp-private-votes').textContent.includes('PABLO'));assert.equal(await page.locator('#mvpVoteResults .confirm-mvp').count(),0);assert.equal(await page.locator('#pendingGoals').isVisible(),false);assert((await page.locator('#mvpVoteResults').textContent()).includes('DIEGO'));
 b.setTime('2026-10-05T23:00:00Z');b.run('closeMvpVoting');await page.evaluate(()=>ChiquiVoting.refresh());await page.waitForFunction(()=>document.querySelector('#featuredMatch').textContent.includes('DIEGO y PABLO'));assert.equal(await points('DIEGO'),'3,5');assert.equal(await points('PABLO'),'1,5');await open();assert(await page.locator('#mvpClosedResult').isVisible());assert((await page.locator('#mvpClosedResult').textContent()).includes('+0,5'));assert(await candidate('DIEGO').isDisabled());
 // A second real match: scorekeeper -> review -> authenticated official result and player goals.
 b.setTime('2026-10-10T23:10:00Z');await page.reload();await ready();await page.locator('#openLiveScore').click();assert.equal(await page.locator('#liveMatchSelect').inputValue(),'3');
 const livePlayer=(team,name)=>page.locator(team==='white'?'#liveWhitePlayers .live-player':'#liveBlackPlayers .live-player').filter({has:page.locator('span',{hasText:new RegExp('^'+name+'$')})});
 await livePlayer('white','LORIA').click();await livePlayer('white','LORIA').click();await livePlayer('black','LUCAS').click();await page.locator('#liveReview').click();assert.equal(calls.filter(x=>x.action==='saveResult').length,0,'review does not publish');await page.locator('#resultForm button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#resultMessage').textContent.includes('finalizada'));assert.equal(calls.filter(x=>x.action==='saveResult').length,1);assert.deepEqual(calls.find(x=>x.action==='saveResult').item.scorers,[{player:'LORIA',team:'white',goals:2},{player:'LUCAS',team:'black',goals:1}]);assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).LORIA,7);assert.equal(await points('LORIA'),'7');
 await page.locator('#openLiveScore').click();assert(await livePlayer('white','LORIA').isDisabled());page.on('dialog',d=>d.accept());await page.locator('#liveReopen').click();await page.locator('#liveUndo').click();await page.locator('#liveBlackPlayers .live-unknown').click();await page.locator('#liveReview').click();assert(await page.locator('#liveScoreDialog').isVisible());assert((await page.locator('#liveScoreMessage').textContent()).includes('sin identificar'));await page.locator('#liveGoalHistory select').selectOption('7');await page.locator('#liveReview').click();await page.locator('#resultForm button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#resultMessage').textContent.includes('finalizada'));assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).LORIA,7);assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).KEVIN,1);assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).LUCAS,4,'correction replaces the original goal author');assert.equal(b.state().matchRecords.length,2,'no duplicate match ledgers after correction');
 // Review blocks a score that disagrees with individual goals.
 await page.locator('#resultWhite').fill('99');await page.locator('#resultForm button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#resultMessage').textContent.includes('no coincide'));assert.equal(calls.filter(x=>x.action==='saveResult').length,2);
 b.setTime('2026-10-12T23:00:00Z');b.run('closeMvpVoting');await page.reload();await ready();assert.equal(await points('LORIA'),'7');assert.equal((await page.evaluate(()=>ChiquiGoals.approvedTotals())).LORIA,7);await open();await page.locator('#mvpMatchSelect').selectOption('3');assert((await page.locator('#mvpClosedResult').textContent()).includes('No hubo votos'));
 await page.evaluate(()=>{Object.keys(localStorage).filter(k=>k.startsWith('chiquimafia_live_score_v1:')).forEach(k=>localStorage.removeItem(k))});await page.reload();await ready();await page.locator('#openLiveScore').click();await page.locator('#liveMatchSelect').selectOption('3');assert.equal(await livePlayer('white','LORIA').locator('b').textContent(),'2');assert.equal(await livePlayer('black','KEVIN').locator('b').textContent(),'1');await page.locator('#closeLiveScore').click();
 // Choosing a future saved match shows a schedule/unavailable state, not enabled voting.
 assert.equal(calls.filter(x=>x.action==='submit'||x.action==='decide'||x.action==='confirmMvp').length,0);assert.deepEqual(errors,[]);
 console.log('PASS: actual Apps Script source + browser; compact 8x8 + voting; confirmation; retry/duplicate/self-vote prevention; PIN-protected live votes; hidden public counts; automatic tie awards/standings; official player goals; unknown-goal assignment; corrected author replaces totals; review/score mismatch; reload; 0 voters; four widths; no real tournament writes.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
